{
  ADC_RefHigh_curr: 7,
  ADC_RefHigh_volt: 30,
  ADC_RefLow_curr: 7,
  ADC_RefLow_volt: 1,
  autoexposure_desired_intensity: 120,
  autoexposure_enabled: true,
  frame_interval: 40000,
  pixel_0_column: 260,
  pixel_0_row: 346,
  pixel_1_column: 260,
  pixel_1_row: 346,
  pixel_2_column: 260,
  pixel_2_row: 346,
  pixel_3_column: 260,
  pixel_3_row: 346,
  pixel_4_column: 260,
  pixel_4_row: 346,
  pixel_5_column: 260,
  pixel_5_row: 346,
  pixel_6_column: 260,
  pixel_6_row: 346,
  pixel_7_column: 260,
  pixel_7_row: 346,
}
